Auth_Autori/routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::view('/login', 'auth.login')->name('auth.login');
Route::view('/register', 'auth.register')->name('auth.register');

Route::post('/register', [AuthController::class, 'register'])->name('auth.register');
Route::post('/login', [AuthController::class, 'login'])->name('auth.login');

Route::middleware('auth')->group(function () {
Route::get('/logout', [AuthController::class, 'logout'])->name('auth.logout');
    Route::resource('profile', Usercontroller::class);
});

Auth_Autori/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
class User extends Authenticatable
{
    use HasFactory;

    protected $fillable = [
      'name',
        'email',
        'password',
        'role'
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

}

Auth_Autori/app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class AuthController extends Controller
{
    public function login(Request $request)
    {
        $credentials = $request->only(['email', 'password']);

        if (Auth::attempt($credentials)) {
            $request->session()->regenerate();
            return redirect('profile');
        } else {
            return back();
        }
    }

    public function logout(Request $request)
    {
        Auth::logout();
        $request->session()->regenerate();
        $request->session()->invalidate();

        return redirect('login');
    }

    public function register(Request $request)
    {
        $customer = new User();
        $customer->name = $request->name;
        $customer->email = $request->email;
        $customer->password = Hash::make($request->password);
        $customer->save();

        return to_route('auth.login');
    }
}

Auth_Autori/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

Auth_Autori/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function index()
    {
        $users = User::all();
        return view('profile', compact('users'));
    }

    public function create()
    {
        return view('admin.create');
    }


    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:3',
            'role' => 'required|',
        ]);
        $user = new User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->role = $request->role;
        $user->save();

        return redirect()
            ->route('profile.index')
            ->with('success', 'User created successfully');
    }

    public function show()
    {
        return view('profile');
    }

    public function edit($id)
    {
        $user = User::find($id);
        return view('admin.edit', compact('user'));
    }


    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $request->validate([
            'u_name' => 'required',
            'u_email' => 'required|email|unique:users,email,',
            'u_role' => 'required',
        ]);
        $userUpdate = [
            'name' => $request->input('u_name'),
            'email' => $request->input('u_email'),
            'role' => $request->input('u_role'),

        ];

        $user->update($userUpdate);
        return redirect()->route('profile.index')->with('success', 'User updated successfully');
    }

    public function destroy($id)
    {
        $users = User::find($id);
        $users->delete();

        return redirect('profile')->with('success', 'User deleted successfully');
    }
}

Auth_Autori/resources/views/Admin/create.blade.php
@extends('layout')
@section('content')
    <h2>Create User</h2>
    <a href="{{route('profile.index')}}">BACK</a>

    <form method="POST" action="{{ route('profile.store') }}">
        @csrf

        <div>
            <label for="name">Name:</label>
            <input type="text" name="name" id="name" required>
        </div>

        <div>
            <label for="email">Email:</label>
            <input type="email" name="email" id="email" required>
        </div>

        <div>
            <label for="password">Password:</label>
            <input type="password" name="password" id="password" required>
        </div>
        <div>
            <label for="role">Role:</label>
            <select name="role" id="role">
                <option value="" selected disabled>Select Role</option>
                <option value="admin">Admin</option>
                <option value="user">User</option>
            </select>
        </div>

        <div>
            <button type="submit">Create User</button>
        </div>
    </form>
@endsection

Auth_Autori/resources/views/Admin/edit.blade.php
@extends('layout')
@section('content')
    <h2>Edit User</h2>
    <a href="{{route('profile.index')}}">BACK</a>
    <form method="POST" action="{{ route('profile.update', $user->id) }}">
        @csrf
        @method('PUT')

        <div>
            <label for="u_name">Name:</label>
            <input type="text" name="u_name" id="u_name" value="{{ old('name', $user->name) }}" required>
        </div>

        <div>
            <label for="u_email">Email:</label>
            <input type="email" name="u_email" id="u_email" value="{{old('email', $user->email) }}" required>
        </div>


        <div>
            <label for="u_role">Role:</label>
            <select name="u_role" id="u_role">
                <option value="" selected disabled>Select Role</option>
                <option value="admin">Admin</option>
                <option value="user">User</option>
            </select>
        </div>

        <div>
            <button type="submit">Update User</button>
        </div>
    </form>
@endsection

Auth_Autori/resources/views/Admin/profile.blade.php
<style>
    table, th, td {
        border: 1px solid black;
    }
</style>

@extends('layout')

@section('content')
    @auth
        @can('isAdmin')
            <h2>Admin Profile</h2>
            <p>Welcome, Admin! You can manage users here.</p>

            <h1>User List</h1>

            <table>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>Settings</th>
                </tr>
                @foreach($users as $user)
                    <tr>
                        <th>{{$user->name}}</th>
                        <th>{{$user->email}}</th>
                        <th>{{$user->role}}</th>
                        <th><a href="{{ route('profile.edit', $user->id) }}">Edit User</a> /
                            <form method="Post" action="{{route('profile.destroy',$user->id)}}">
                                @csrf
                                @method('DELETE')
                                <button type="submit">Delete User</button>
                            </form>
                        </th>

                    </tr>
                @endforeach
            </table>
            <a href="{{ route('profile.create') }}">Create User</a>

        @else
            <h2>User Profile</h2>
            <p>Hello, {{ auth()->user()->name }}</p>
            <p><strong>Name:</strong> {{ auth()->user()->name }}</p>
            <p><strong>Email:</strong> {{ auth()->user()->email }}</p>
        @endif
    @endauth
@endsection

Auth_Autori/resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Laravel App</title>
</head>
<body>
<nav>
    <ul>
        @can(Auth::user())
            <li><a href="{{ route('auth.login') }}">Login</a></li>
            <li><a href="{{ route('auth.register') }}">Register</a></li>
        @endcan
        @auth
            <li><a href="{{ route('auth.logout') }}">Logout</a></li>
        @endauth
    </ul>
</nav>
@yield('content')

</body>
</html>

Auth_Autori/resources/views/profile.blade.php
<style>
    table, th, td {
        border: 1px solid black;
    }
</style>

@extends('layout')

@section('content')
    @auth
        @can('isAdmin')
            <h2>Admin Profile</h2>
            <p>Welcome, Admin! You can manage users here.</p>

            <h1>User List</h1>

            <table>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>Settings</th>
                </tr>
                @foreach($users as $user)
                    <tr>
                        <th>{{$user->name}}</th>
                        <th>{{$user->email}}</th>
                        <th>{{$user->role}}</th>
                        <th><a href="{{ route('profile.edit', $user->id) }}">Edit User</a> /
                            <form method="Post" action="{{route('profile.destroy',$user->id)}}">
                                @csrf
                                @method('DELETE')
                                <button type="submit">Delete User</button>
                            </form>
                        </th>

                    </tr>
                @endforeach
            </table>
            <a href="{{ route('profile.create') }}">Create User</a>

        @else
            <h2>User Profile</h2>
            <p>Hello, {{ auth()->user()->name }}</p>
            <p><strong>Name:</strong> {{ auth()->user()->name }}</p>
            <p><strong>Email:</strong> {{ auth()->user()->email }}</p>
        @endif
    @endauth
@endsection